name: voiceye
description: A Flutter application can read values on post machine

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  screentheme: ^0.0.2
  camera: 0.5.7+3
  path_provider: 1.5.1
  firebase_storage: ^3.1.1
  dio: 3.0.8
  http: 0.12.0+4
  mobx: ^0.3.10
  flutter_mobx: ^0.3.4+1
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^0.3.10+1

flutter:
  uses-material-design: true